In [10]:
import numpy as np
a2=np.array([[0,1,2,3],
             [4,5,6,7],
                [8,9,10,11]])
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Slicing for 2 D array


### array[row_start:row_stop:row_step, column_start:column_stop:column_step]

In [11]:
# now we need to find the 5,6
#                         9,10
# from the given array using slicing
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [12]:
# now we need to find the 0,3
#                         8,11
# from the given array using slicing
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [13]:
# now we need to find the 1,3
#                         9,11
# from the given array using slicing
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [14]:
# now we need to find the 1,2,3
#                         5,6,7
# from the given array using slicing
a2[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

# Now we need to do sclicing for 3-D array

In [15]:
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [16]:
# now we need to find the 9,10,11
#                         12,13,14
#                         15,16,17
# from the given array using slicing
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
# now we need to find the 0,1,2
#                         3,4,5 
#                         6,7,8

#                          18,19,20
#                          21,22,23
#                          24,25,26
# from the given array using slicing
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [22]:
# now we need to find the 3,4,5
# from the given array using slicing
a3[0,1,:]

array([3, 4, 5])

In [24]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [25]:
# now we need to find the 10,13,16
# from the given array using slicing
a3[1,:,1]

array([10, 13, 16])

In [29]:
# now we need to find the 22,23
#                         25,26
# from the given array using slicing
a3[2,1::,1::]

array([[22, 23],
       [25, 26]])

In [32]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [50]:
# now we need to find the 0,2
#                         18,20
# from the given array using slicing
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])