In [2]:
import numpy as np
a2=np.array([[0,1,2,3],
             [4,5,6,7],
                [8,9,10,11]])
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Slicing for 2 D array


### array[row_start:row_stop:row_step, column_start:column_stop:column_step]

In [3]:
# now we need to find the 5,6
#                         9,10
# from the given array using slicing
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [4]:
# now we need to find the 0,3
#                         8,11
# from the given array using slicing
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [5]:
# now we need to find the 1,3
#                         9,11
# from the given array using slicing
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [6]:
# now we need to find the 1,2,3
#                         5,6,7
# from the given array using slicing
a2[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

# Now we need to do sclicing for 3-D array

In [8]:
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [9]:
# now we need to find the 9,10,11
#                         12,13,14
#                         15,16,17
# from the given array using slicing
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])