In [2]:
import numpy as np
a2=np.array([[0,1,2,3],
             [4,5,6,7],
               [8,9,10,11]])
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Slicing for 2 D array


### array[row_start:row_stop:row_step, column_start:column_stop:column_step]

In [3]:
# now we need to find the 5,6
#                         9,10
# from the given array using slicing
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [4]:
# now we need to find the 0,3
#                         8,11
# from the given array using slicing
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [5]:
# now we need to find the 1,3
#                         9,11
# from the given array using slicing
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [6]:
# now we need to find the 1,2,3
#                         5,6,7
# from the given array using slicing
a2[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

# Now we need to do sclicing for 3-D array

In [7]:
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [8]:
# now we need to find the 9,10,11
#                         12,13,14
#                         15,16,17
# from the given array using slicing
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [9]:
# now we need to find the 0,1,2
#                         3,4,5 
#                         6,7,8

#                          18,19,20
#                          21,22,23
#                          24,25,26
# from the given array using slicing
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
# now we need to find the 3,4,5
# from the given array using slicing
a3[0,1,:]

array([3, 4, 5])

In [11]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
# now we need to find the 10,13,16
# from the given array using slicing
a3[1,:,1]

array([10, 13, 16])

In [13]:
# now we need to find the 22,23
#                         25,26
# from the given array using slicing
a3[2,1::,1::]

array([[22, 23],
       [25, 26]])

In [14]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [15]:
# now we need to find the 0,2
#                         18,20
# from the given array using slicing
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

### Fancy Indexing

In [16]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [17]:
a= np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [18]:
# now we need to find the[0  1  2  3  4
#                         5  6  7  8  9
#                         15 16 17 18 19
# from the given array using Fancy indexing
a[[0,1,3]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [19]:
# now we need to find the
# [1  2  4]
# [6  7  9]
# [11 1 14]
# [16 17 19]
# from the given array using Fancy indexing
a[:,[1,2,4]]

array([[ 1,  2,  4],
       [ 6,  7,  9],
       [11, 12, 14],
       [16, 17, 19]])

 #### Boolean Indexing 

In [25]:
# Just making an normal array using the random number generator 
x= np.random.randint (1,100,24).reshape(6,4)

In [26]:
print(x)

[[64 43 43 94]
 [71 83 60 76]
 [99 89 87 95]
 [77 55 40 76]
 [75 73 65  2]
 [ 9 13 72  2]]


In [27]:
# find all the numver that is grater then 50
x>50

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [False, False,  True, False]])

In [29]:
# now we will only keep the numbers that are true in the matrix 
x[x>50]

array([64, 94, 71, 83, 60, 76, 99, 89, 87, 95, 77, 55, 76, 75, 73, 65, 72],
      dtype=int32)

In [30]:
# find the numbers that are even in the given array
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
# Now we need to find the numbers that are  greter then 50 and are even
x[(x>50)&(x%2==0)]

array([64, 94, 60, 76, 76, 72], dtype=int32)

### Brodcasting 

In [35]:
y=np.arange(6).reshape(2,3)
z=np.arange(3).reshape(1,3)
print(y)
print(z)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


In [ ]:
# Now we need to joithe both array

